# Solving Linear Equation

https://www.eecis.udel.edu/~boncelet/ipynb/LR_NYC_Example.html

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
np.c_[[1, 2], [3, 4]]

array([[1, 3],
       [2, 4]])

In [3]:
np.stack([[1, 2], [3, 4]], axis=1)

array([[1, 3],
       [2, 4]])

In [4]:
X = 2 * np.random.rand(100)
y = 4 + 3 * X + np.random.randn(100)

## Solving the normal equation manually

In [5]:
# Add 1 as bias term for x0
X_b = np.stack([np.ones(100), X], axis=1)
theta = np.linalg.pinv(X_b.T @ X_b) @ (X_b.T @ y)
theta

array([3.92514127, 2.98895247])

In [6]:
X_test = [1, 5]
X_test @ theta

18.869903640101324

In [7]:
X_b = np.stack([np.ones(X.shape[0]), X], axis=1)
theta, residuals, rank, s = np.linalg.lstsq(X_b, y)
theta

/var/folders/v5/8v9k6wcn65jbbct8spl3wwsh0000gn/T/ipykernel_15162/1142066073.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  theta, residuals, rank, s = np.linalg.lstsq(X_b, y)


array([3.92514127, 2.98895247])

In [8]:
X_test @ theta

18.86990364010136

In [9]:
theta = np.linalg.solve(X_b.T @ X_b, X_b.T @ y)
theta

array([3.92514127, 2.98895247])

In [10]:
X_test @ theta

18.869903640101292

## Using statsmodels

In [11]:
import statsmodels.api as sm

model = sm.OLS(y, sm.add_constant(X))
results = model.fit()
results.params

array([3.92514127, 2.98895247])

In [12]:
model.predict(results.params, exog=X_test)

18.869903640101352

## Using Scikit-Learn

In [13]:
model = LinearRegression()
model.fit(X.reshape(-1, 1), y)

LinearRegression()

In [14]:
model.coef_

array([2.98895247])

In [15]:
model.intercept_

3.9251412676244635

In [16]:
model.predict([[5]])

array([18.86990364])